# Generated by Django 3.1.1 on 2020-09-23 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('steps', models.IntegerField(default=0)),
                ('guide_file', models.FileField(upload_to='guides/')),
                ('animation_file', models.FileField(upload_to='animations/')),
                ('status', models.CharField(choices=[('QUE', 'Queued'), ('PRO', 'Processing'), ('ERR', 'Error'), ('DON', 'Done')], default='QUE', max_length=32)),
                ('private', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
