# Generated by Django 3.1.1 on 2020-09-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='status',
            field=models.CharField(choices=[('QUE', 'Queued'), ('PRO', 'Processing'), ('TMO', 'Timeout'), ('ERR', 'Error'), ('DON', 'Done')], default='QUE', max_length=32),
        ),
    ]
