version: '3.8'

x-shared_environment: &shared-environment
  CELERY_BROKER_URL: redis://redis:6379
  CELERY_RESULT_BACKEND: redis://redis:6379
  MEDIA_ROOT: /files
  DATABASE_ENGINE: django.db.backends.postgresql
  DATABASE_NAME: origuide
  DATABASE_HOST: postgres
  DATABASE_PORT: 5432

volumes:
  postgres:
  redis:
  guides:

networks:
  origuide:
  proxy-tier:
    external:
      name: nginx-proxy

services:
  postgres:
    image: postgres:13
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - origuide
  redis:
    image: redis:6
    networks:
      - origuide
    volumes:
      - redis:/data
    restart: always
  worker:
    image: origuide/worker:master
    env_file: .env
    networks:
      - origuide
    environment:
      <<: *shared-environment
    volumes:
      - guides:/files
    depends_on:
      - postgres
      - migrations
    restart: always
  community:
    image: origuide/community:master
    env_file: .env
    networks:
      - origuide
      - proxy-tier
    environment:
      <<: *shared-environment
      VIRTUAL_HOST: api.origami.wtf
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: api.origami.wtf
      LETSENCRYPT_EMAIL: noreply@origami.wtf
    volumes:
      - guides:/files
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - postgres
      - migrations
    restart: always
  migrations:
    image: origuide/community:master
    env_file: .env
    environment:
      <<: *shared-environment
    command: python /community/manage.py migrate
    networks:
      - origuide
    depends_on:
      - postgres