services:
  community:
    command: python /community/manage.py runserver 0.0.0.0:8000 
    environment:
      PYTHONUNBUFFERED: "yeah"
    volumes:
      - guides:/files
      - ./community:/community
  migrations:
    command: python /community/manage.py migrate
    volumes:
      - guides:/files
      - ./community:/community
