version: '3'

x-shared_environment: &shared-environment
  CELERY_BROKER_URL: redis://redis:6379
  CELERY_RESULT_BACKEND: redis://redis:6379
  MEDIA_ROOT: /files
  DATABASE_ENGINE: django.db.backends.postgresql
  DATABASE_NAME: origuide
  DATABASE_HOST: postgres
  DATABASE_PORT: 5432

volumes:
  postgres:
  redis:
  guides:

services:
  postgres:
    image: postgres:13
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis:6
    volumes:
      - redis:/data
    restart: always
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file: .env
    environment:
      <<: *shared-environment
    volumes:
      - guides:/files
    depends_on:
      - postgres
      - migrations
    restart: always
  community:
    build:
      context: .
      dockerfile: Dockerfile.community
    env_file: .env
    environment:
      <<: *shared-environment
    volumes:
      - guides:/files
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - postgres
      - migrations
    restart: always
  migrations:
    build:
      context: .
      dockerfile: Dockerfile.community
    env_file: .env
    environment:
      <<: *shared-environment
    command: python /community/manage.py migrate
    depends_on:
      - postgres