version: '3'

volumes:
  postgres:
  redis:
  guides:

services:
  postgres:
    image: postgres:13
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:6
    volumes:
      - redis:/data
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file: .env
    volumes:
      - guides:/files
    depends_on:
      - postgres
      - migrations
  community:
    build:
      context: .
      dockerfile: Dockerfile.community
    env_file: .env
    volumes:
      - guides:/files
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - migrations
  migrations:
    build:
      context: .
      dockerfile: Dockerfile.community
    env_file: .env
    command: python /community/manage.py migrate
    depends_on:
      - postgres