# Generated by Django 3.1.1 on 2020-10-09 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_guides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guide',
            name='solved_by',
            field=models.ManyToManyField(related_name='solved_guides', to=settings.AUTH_USER_MODEL),
        ),
    ]
