# Generated by Django 3.1.1 on 2020-10-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_auto_20201009_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='thumbnail_file',
            field=models.ImageField(default=None, null=True, upload_to='thumbnails/'),
        ),
    ]
