name: Frontend

on:
  push:
    branches: [ master ]
    paths:
    - 'frontend/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'frontend/**'

defaults:
  run:
    shell: bash
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
    - uses: actions/upload-artifact@v1
      with:
        name: frontend.zip
        path: frontend/dist
