name: Thesis

on:
  push:
    branches: [ master ]
    paths:
    - 'thesis/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'thesis/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Github Action for LaTeX
      uses: xu-cheng/latex-action@1.2.1
      with:
        root_file: thesis.tex
        working_directory: thesis
    - uses: actions/upload-artifact@v1
      with:
        name: thesis.pdf
        path: thesis/thesis.pdf
